name: illustrashirt
description: Flutter e-commerce application for Illustrashirt.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  introduction_screen: ^1.0.9
  shared_preferences: ^2.0.6
  dio: ^4.0.0
  shimmer: ^1.1.2
  connectivity: ^3.0.6
  provider: ^4.3.3
  focused_menu: ^1.0.5
  import_js_library: ^1.0.2
  image_picker: ^0.8.2
  image_cropper: ^1.4.1
  fluttertoast: ^8.0.7

  http:

  # database :
  sqflite: ^2.0.0+3

  # format date :
  intl: ^0.17.0

  # display in grid :
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3

  # firebase :
  cloud_firestore: ^2.3.0
  firebase_storage: ^9.0.0
  firebase_core: ^1.3.0
  firebase_database: ^7.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/categories/
    - assets/images/onBoardings/
    - assets/path/
    - assets/filter/






  fonts:
     - family: Quincy
       fonts:
         - asset: fonts/QuincyCF-Regular.otf

     - family: Poppin
       fonts:
         - asset: fonts/Poppins-Regular.ttf

